# we only need to point to python for the tests to run
language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"

# command to install dependencies
install:
#  - pip install -r requirements
  - pip install flake8

# command to run before the tests
before_script:
  - "flake8 seyiranalyzer --ignore=E501"

# command to run tests
script:
#  - nosetests unittests
  - nosetests --with-coverage
